### ISSUE TITLE
Why two licenses

### ISSUE THREAD

**Issue by GaryBAYLOR** [blind-contours/CVtreeMLE#2]
I noticed there are two license files for the package. Can you explain besides MIT license, what's the license in the plain file `LICENSE`, and what's the purpose of having two licenses for the package?

**Comment by blind-contours** [comment]
Hi @GaryBAYLOR, thank you -- the second license has been removed and the exiting MIT license has been updated to 2022 and matches the license listed in the READme.

**Comment by GaryBAYLOR** [comment]
The license in the DESCRIPTION file is still: `MIT + file LICENSE`, not aligning with the one in LICENSE file and README, which is MIT only

**Comment by blind-contours** [comment]
I've removed the + LICENSE in description so there should be just one now - thanks for spotting this.
