### ISSUE TITLE
Add Windows to build CI workflow

### ISSUE THREAD

**Issue by wleoncio** [blind-contours/CVtreeMLE#25]
I noticed the [build CI file](https://github.com/blind-contours/CVtreeMLE/actions/runs/3849846438/workflow) contains Linux and macOS builds. It would be nice to also include a Windows check in there (even if that's the platform you're developing on), so that the tests are more comprehensibe by including non-Unix OSs, and would benefit contributors not on Windows machines (there are dozens of us. Dozens!)

**Comment by blind-contours** [comment]
Hi @wleoncio - I've added windows to the build file. I think originally I removed this because a version of SL3@devel was failing install on windows and I couldn't figure out why (not related to CVtreeMLE). I've added it back and I'll see if it passes the tests on Windows now.

**Comment by wleoncio** [comment]
Thanks for taking care of this. The Windows check seems to still contain an SL3-related issue, but I would rather have an issue opened to take care of it later than drop the OS check altogether.
