### ISSUE TITLE
Introducing packages in the order of their installation dependency in README

### ISSUE THREAD

**Issue by GaryBAYLOR** [blind-contours/CVtreeMLE#28]
I encountered the following error when following instructions in README to run `remotes::install_github("blind-contours/CVtreeMLE@main")`:
```r
ERROR: package installation failed
Error: Failed to install 'CVtreeMLE' from GitHub:
  Failed to install 'sl3' from GitHub:
```
Please check dependencies among the following packages introduced in README file, and describe them in the order that, if installation of A will fail because B hasn't been installed, introduce B before A.

```r
remotes::install_github("blind-contours/CVtreeMLE@main")
remotes::install_github("tlverse/sl3@devel")
install.packages("partykit")
install.packages("pre")
install.packages(c("kableExtra", "ranger", "arm", "xgboost", "nnls", "hrbrthemes", "viridis"))
```

**Comment by blind-contours** [comment]
Sorry about that - I've just updated the readme to have things in the correct sequence for installation.
