### ISSUE TITLE
Lightweight editing of the JOSS paper

### ISSUE THREAD

**Issue by GaryBAYLOR** [blind-contours/CVtreeMLE#5]
`line 10:` glm --> GLM
`line 30:` Thus --> Therefore
`line 39`: glm's --> GLMs
`line 48, line 50`: semiparametric --> semi-parametric
`line 58`: unbold "a priori" and change it to italic format
`line 69`: average treatment effect --> average treatment effect (ATE).  The reason is, when using an acronym, state it when it first appears in the paper and only use the acronym through the rest of the paper.
`line 84`: average treatment effect (ATE) --> ATE
`line 87-88`:  Remove 'language and environment for statistical computing'
`line 91`: CVtreeMLE --> It
`line 92`: sl3package --> sl3 package
`line 95-96`: the hyperlink to CRAN is invalid as the package hasn't been published there. 
`line 102-103`: To make sure the title of the reference matches with the title in DOI, sl3: Modern pipelines for machine learning and Super Learning --> sl3: Modern super learning with pipelines
`line 105-106`: Statistical Inference for Data Adaptive Target Parameters --> Statistical inference for data adaptive target parameters.  This is to make all the references look consistent.

**Comment by ghost** [comment]
I'll add some assorted comments here, in addition to the above:

- first sentence contains broad generalization (e.g. `in most cases`) that I think weakens the presentation overall. that can be addressed later, and should involve specific examples
- direct reference to existing tools e.g. marginal models is essential here; certainly GLMs are a major offender here, but I think being as precise as possible strengthens the assertion that the package is needed
- I mention this in the vignette issue as well, but I think defining what is meant by `asymptotically` here is important: how can we evaluate if our data and models are appropriate for this package, or that we can expect reasonable convergence?
- the background section contains non-background content that is best included elsewhere or pared down
- how are guarantees in line 75 being proven? it seems like this in part relies on behavior of sl3. in any case, these guarantees should be elaborated upon

**Comment by ghost** [comment]
In terms of the review checklist, I think the two points `description [...] for a diverse, non-specialist audience` and `clearly states [...] who the target audience is` could both use further elaboration and expansion. The author is very clearly knowledgeable about the methodology in use here. I think the target audience would likely be users of standard marginal models (e.g. GLM), but observe that many such users are specifically using GLMs because they understand basic regression models but are perhaps not as comfortable with more advanced ML techniques. I think including some content that specifically reaches out to such users, if indeed they are part of the intended user set, would be most welcome.

**Comment by blind-contours** [comment]
@GaryBAYLOR I have made edits to the paper based on your comments. @cpalmer718 I have done some rewriting to reference existing methods and lay a quick but better foundation as to the methodological gap this method/software is filling. I've added some additional details as to asymptotic convergence and under what assumptions we have an efficient rate of convergence. I have also rewritten sections of the background.

**Comment by GaryBAYLOR** [comment]
@blind-contours Looks good. Just one very minor comment, be consistent in writing `nonparametric`, either `non-parameter` or `nonparametric` is okay (line 18, 19, 30, 44)

@cpalmer718 I'm good on my comments. Please feel free to close the issue when the questions in your comments are addressed.

**Comment by blind-contours** [comment]
I've updated the md document to be consistent in using non-parametric.
